name: auction
version: '1.0.0'
main: me.optif1ne.auction.Auction
api-version: '1.20'
softdepend: [Vault]

commands:
  auction:
    description: Основная команда аукциона
    usage: /auction <add|...>
    aliases: [auc]

permissions:
  auction.use:
    description: Открывать аукцион и пользоваться GUI
    default: true
  auction.add:
    description: Выставлять лоты
    default: true
  auction.buy:
    description: Покупать лоты
    default: true